services:
  - type: web
    name: pdf-toolkit-server
    env: node
    root: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome-stable
      - key: NODE_VERSION
        value: 20.11.0
